"""
Generator for migrations/phase_7_nt_role.sql

Phase 7 adds:
  1. `evaluations.created_by_role VARCHAR(32) NOT NULL`. Backfilled to
     'scout' for all existing rows (every current user with evaluations
     is a scout). Indexed for the visibility filter.
  2. The `users_role_check` constraint is *widened* (NOT replaced) to
     accept the new `nt_staff` role. The 4 existing roles
     (admin, technical_director, scout, viewer) are PRESERVED — the
     original spec proposed replacing the set with
     (admin, scout, coach, management, nt_staff), which would have
     silently dropped TD and viewer from the allowed set and broken
     four existing role-decorators. Final allowed set:
     (admin, technical_director, scout, viewer, nt_staff).

Pre-flight gates inside the emitted SQL:
  - Aborts if `evaluations.created_by_role` already exists (one-shot
    apply guard).
  - Aborts if there are any non-NULL rows in `created_by_role`
    inconsistent with the backfill (shouldn't happen on first run;
    defensive).

Audit gate:
  - After backfill, every active+deleted evaluation must have
    `created_by_role` set; the count of 'scout'-tagged rows must
    equal the total evaluation count (everyone today is a scout).
"""
import sys
from pathlib import Path

sys.path.insert(0, str(Path(__file__).resolve().parent.parent))


# Both formats; this layer is documentation-only — the migration uses
# the wider set we lock in below.
ROLE_SET_BEFORE = ('admin', 'technical_director', 'scout', 'viewer')
ROLE_SET_AFTER  = ('admin', 'technical_director', 'scout', 'viewer', 'nt_staff')

print("Phase 7 role-set transition:")
print(f"  before: {ROLE_SET_BEFORE}")
print(f"  after:  {ROLE_SET_AFTER}")
assert set(ROLE_SET_BEFORE).issubset(set(ROLE_SET_AFTER)), \
    "ROLE_SET_AFTER must be a superset of ROLE_SET_BEFORE (no data scrub allowed)"
print("  ADDITIVE (no role dropped)\n")


SQL = """\
-- =============================================================
-- BFA-Scout — Phase 7 NT staff role + evaluation visibility
-- Generated by migrations/_generate_phase_7.py
-- =============================================================
-- Effects:
--   1. Pre-flight: aborts if `evaluations.created_by_role` column
--      already exists (one-shot apply guard).
--   2. ADD COLUMN evaluations.created_by_role VARCHAR(32) (nullable
--      initially, so we can backfill in a single transaction).
--   3. Backfill: every existing evaluation row gets 'scout' (current
--      DB users are 1 admin + 1 scout; only scouts have created any
--      evaluations).
--   4. Set NOT NULL on created_by_role after the backfill.
--   5. Index for the visibility filter.
--   6. Widen `users_role_check` to add 'nt_staff' while keeping the
--      existing roles (admin, technical_director, scout, viewer).
--   7. Audit gate: all rows backfilled; 'scout'-tagged count == total.
-- =============================================================

\\set ON_ERROR_STOP on
\\timing on

-- ─── Pre-flight (no transaction yet) ───────────────────────────
DO $$
DECLARE
  col_exists BOOLEAN;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE  table_schema = current_schema()
      AND  table_name   = 'evaluations'
      AND  column_name  = 'created_by_role'
  ) INTO col_exists;
  IF col_exists THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — evaluations.created_by_role already exists; migration already applied';
  END IF;
END $$;

BEGIN;

-- ─── 1. ADD COLUMN (nullable until backfill completes) ──────────
ALTER TABLE evaluations
  ADD COLUMN created_by_role VARCHAR(32);

-- ─── 2. Backfill every existing eval to 'scout' ─────────────────
-- All current evaluations were created when the only frontline role
-- was 'scout'. Admin users have not authored evaluations in this DB
-- as of the audit query at the top of the spec.
UPDATE evaluations
SET    created_by_role = 'scout'
WHERE  created_by_role IS NULL;

-- ─── 3. Now NOT NULL ────────────────────────────────────────────
ALTER TABLE evaluations
  ALTER COLUMN created_by_role SET NOT NULL;

-- ─── 4. Index for the visibility filter ─────────────────────────
CREATE INDEX IF NOT EXISTS idx_evaluations_created_by_role
  ON evaluations(created_by_role);

-- ─── 5. Widen users_role_check (additive — preserves the 4 existing roles)
ALTER TABLE users DROP CONSTRAINT IF EXISTS users_role_check;
ALTER TABLE users ADD CONSTRAINT users_role_check
  CHECK (role IN ('admin', 'technical_director', 'scout', 'viewer', 'nt_staff'));

-- ─── 6. Audit gate (RAISE → ROLLBACK on drift) ──────────────────
DO $$
DECLARE
  total      INT;
  scout_n    INT;
  null_n     INT;
BEGIN
  SELECT COUNT(*) INTO total    FROM evaluations;
  SELECT COUNT(*) INTO scout_n  FROM evaluations WHERE created_by_role = 'scout';
  SELECT COUNT(*) INTO null_n   FROM evaluations WHERE created_by_role IS NULL;
  IF null_n > 0 THEN
    RAISE EXCEPTION 'AUDIT FAIL — % evaluations with NULL created_by_role', null_n;
  END IF;
  IF scout_n != total THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected % rows tagged scout, got %', total, scout_n;
  END IF;
  RAISE NOTICE 'AUDIT PASS — % evaluations backfilled to created_by_role=scout', total;
END $$;

COMMIT;

-- ─── Eyeball table (post-commit) ───────────────────────────────
SELECT created_by_role, COUNT(*) AS n
FROM   evaluations
GROUP  BY created_by_role
ORDER  BY created_by_role NULLS FIRST;
"""

out = Path(__file__).parent / "phase_7_nt_role.sql"
out.write_text(SQL, encoding="utf-8")
print(f"Wrote {out}  ({out.stat().st_size:,} bytes)")
