"""
Generator for migrations/phase_5b_matches.sql

Same artifact split as Phase 5a — generator script holds the expected
counts, the SQL is mechanically derived. Re-run after any threshold
change.

Run from repo root:
    python migrations/_generate_phase_5b.py

Writes:
    migrations/phase_5b_matches.sql
"""
from pathlib import Path

# ── Expected pre-flight + audit counts (corrected for Bouhra import) ──
EXPECTED_STATS_BEFORE   = 34   # Arthur 18 + Bouhra 16
EXPECTED_MATCHES_AFTER  = 33   # 34 stat rows - 1 shared fixture (Muharraq vs Khalidiya 2026-01-02)
EXPECTED_LINKED_AFTER   = 34   # every stat row links
EXPECTED_UNLINKED_AFTER = 0


SQL_TEMPLATE = """\
-- =============================================================
-- BFA-Scout — Phase 5b reseed migration
-- Generated by migrations/_generate_phase_5b.py
-- =============================================================
-- Effects:
--   1. Pre-flight: aborts unless wyscout_match_stats has exactly
--      {expected_stats} rows AND the matches table does not yet exist.
--   2. Creates matches table (11 cols, UNIQUE + 4 indexes).
--   3. Adds match_id column + index to wyscout_match_stats.
--   4. Backfills: INSERT DISTINCT (date, home, away) → matches;
--      UPDATE wyscout_match_stats.match_id via case-insensitive join.
--   5. Audit gate raises (forcing ROLLBACK) unless:
--        matches == {expected_matches}, linked == {expected_linked},
--        unlinked == {expected_unlinked}.
-- =============================================================

\\set ON_ERROR_STOP on
\\timing on

-- ─── Pre-flight (no transaction yet) ───
DO $$
DECLARE
  s_count INT;
  m_exists BOOLEAN;
BEGIN
  SELECT to_regclass('public.matches') IS NOT NULL INTO m_exists;
  IF m_exists THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — matches table already exists';
  END IF;
  SELECT COUNT(*) INTO s_count FROM wyscout_match_stats;
  IF s_count != {expected_stats} THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — expected % wyscout_match_stats rows, found %',
      {expected_stats}, s_count;
  END IF;
END $$;

BEGIN;

-- ─── Create matches table ───
CREATE TABLE matches (
    id              SERIAL PRIMARY KEY,
    match_date      DATE         NOT NULL,
    home_team       VARCHAR(128) NOT NULL,
    away_team       VARCHAR(128) NOT NULL,
    home_score      INTEGER,
    away_score      INTEGER,
    competition     VARCHAR(128),
    age_group       VARCHAR(16)
                    CHECK (age_group IN ('senior','u23','u20','u17') OR age_group IS NULL),
    match_type      VARCHAR(32)
                    CHECK (match_type IN ('league','cup','friendly','tournament','national_team') OR match_type IS NULL),
    bfa_team_side   VARCHAR(8)
                    CHECK (bfa_team_side IN ('home','away') OR bfa_team_side IS NULL),
    notes           TEXT,
    source          VARCHAR(16) NOT NULL DEFAULT 'manual'
                    CHECK (source IN ('wyscout','manual')),
    created_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
    created_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    updated_at      TIMESTAMPTZ NOT NULL DEFAULT NOW(),
    UNIQUE (match_date, home_team, away_team)
);

CREATE INDEX idx_matches_lookup
    ON matches (match_date, LOWER(BTRIM(home_team)), LOWER(BTRIM(away_team)));
CREATE INDEX idx_matches_age_group ON matches (age_group);
CREATE INDEX idx_matches_source    ON matches (source);
CREATE INDEX idx_matches_date      ON matches (match_date);

-- ─── Add match_id to wyscout_match_stats ───
ALTER TABLE wyscout_match_stats
    ADD COLUMN match_id INTEGER REFERENCES matches(id) ON DELETE SET NULL;
CREATE INDEX idx_wyscout_match_id ON wyscout_match_stats (match_id);

-- ─── Backfill matches from existing stat rows ───
-- Insert one matches row per unique (date, home, away) tuple.
-- Source = 'wyscout' (came from xlsx data). created_by = first admin we find.
INSERT INTO matches
    (match_date, home_team, away_team, home_score, away_score,
     competition, source, created_by)
SELECT DISTINCT
    match_date,
    home_team,
    away_team,
    home_score,
    away_score,
    competition,
    'wyscout',
    (SELECT id FROM users WHERE role = 'admin' AND is_active = TRUE
        ORDER BY id LIMIT 1)
FROM wyscout_match_stats
WHERE match_date IS NOT NULL
  AND (home_team IS NOT NULL OR away_team IS NOT NULL)
ON CONFLICT (match_date, home_team, away_team) DO NOTHING;

-- ─── Link existing stat rows to their matches via case-insensitive join ───
UPDATE wyscout_match_stats wms
SET match_id = m.id
FROM matches m
WHERE wms.match_date = m.match_date
  AND LOWER(BTRIM(wms.home_team)) = LOWER(BTRIM(m.home_team))
  AND LOWER(BTRIM(wms.away_team)) = LOWER(BTRIM(m.away_team))
  AND wms.match_id IS NULL;

-- ─── Audit gate ───
DO $$
DECLARE
  m_count   INT;
  linked    INT;
  unlinked  INT;
BEGIN
  SELECT COUNT(*) INTO m_count  FROM matches;
  SELECT COUNT(*) INTO linked   FROM wyscout_match_stats WHERE match_id IS NOT NULL;
  SELECT COUNT(*) INTO unlinked FROM wyscout_match_stats WHERE match_id IS NULL;

  IF m_count != {expected_matches} THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected % matches, got %',
      {expected_matches}, m_count;
  END IF;
  IF linked != {expected_linked} THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected % linked stat rows, got %',
      {expected_linked}, linked;
  END IF;
  IF unlinked != {expected_unlinked} THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected % unlinked stat rows, got %',
      {expected_unlinked}, unlinked;
  END IF;
  RAISE NOTICE 'AUDIT PASS — % matches, % linked, % unlinked', m_count, linked, unlinked;
END $$;

-- ─── Eyeball verification (ordered by date) ───
SELECT m.id, m.match_date, m.home_team, m.away_team,
       (SELECT COUNT(*) FROM wyscout_match_stats WHERE match_id = m.id) AS linked_stats
FROM matches m
ORDER BY m.match_date, m.id;

COMMIT;
"""


def main():
    sql = SQL_TEMPLATE.format(
        expected_stats=EXPECTED_STATS_BEFORE,
        expected_matches=EXPECTED_MATCHES_AFTER,
        expected_linked=EXPECTED_LINKED_AFTER,
        expected_unlinked=EXPECTED_UNLINKED_AFTER,
    )
    out = Path(__file__).parent / "phase_5b_matches.sql"
    out.write_text(sql, encoding="utf-8")
    n_lines = sql.count("\n") + 1
    print(f"Wrote {out} ({n_lines} lines)")
    print(f"Pre-flight: wyscout_match_stats == {EXPECTED_STATS_BEFORE}")
    print(f"Audit:      matches == {EXPECTED_MATCHES_AFTER}, "
          f"linked == {EXPECTED_LINKED_AFTER}, unlinked == {EXPECTED_UNLINKED_AFTER}")


if __name__ == "__main__":
    main()
