"""
Generator for migrations/phase_5c1_1_na_column.sql

Phase 5c-1.1 — tri-state slider schema:
  - evaluation_scores.is_not_applicable BOOLEAN NOT NULL DEFAULT FALSE  (new)
  - evaluation_scores.score: drop NOT NULL                              (changed)
  - evaluation_scores_score_or_na CHECK constraint                      (new)

Pre-flight asserts the 14 existing rows are all valid (score set, not-NA).
Audit gate confirms post-state: column added, constraint present, every
row satisfies the tri-state invariant.
"""
from pathlib import Path

EXPECTED_ROWS_BEFORE = 14   # Arthur 5 + Bouhra 9 + Empty 0 = 14

SQL_TEMPLATE = """\
-- =============================================================
-- BFA-Scout — Phase 5c-1.1 tri-state slider schema migration
-- Generated by migrations/_generate_phase_5c1_1.py
-- =============================================================
-- Effects:
--   1. Pre-flight: aborts if is_not_applicable already exists, or if any
--      existing row has score IS NULL (would already violate the new
--      invariant).
--   2. ADD COLUMN is_not_applicable (defaults to FALSE — backfills cleanly).
--   3. DROP NOT NULL on score (so N/A rows can have score IS NULL).
--   4. ADD CHECK constraint enforcing the tri-state invariant:
--        (score IS NOT NULL AND is_not_applicable = FALSE)  -- rated
--        OR (score IS NULL AND is_not_applicable = TRUE)    -- N/A
--      Untouched is "no row" — naturally enforced by absence.
--   5. Audit gate: every row satisfies the invariant.
-- =============================================================

\\set ON_ERROR_STOP on
\\timing on

-- ─── Pre-flight ───
DO $$
DECLARE
  col_exists BOOLEAN;
  null_score_count INT;
  total_rows INT;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name = 'evaluation_scores'
      AND column_name = 'is_not_applicable'
  ) INTO col_exists;
  IF col_exists THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — is_not_applicable column already exists';
  END IF;

  SELECT COUNT(*) INTO null_score_count FROM evaluation_scores WHERE score IS NULL;
  IF null_score_count > 0 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — % rows have score IS NULL pre-migration', null_score_count;
  END IF;

  SELECT COUNT(*) INTO total_rows FROM evaluation_scores;
  IF total_rows != {expected_rows} THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — expected % evaluation_scores rows, found %',
      {expected_rows}, total_rows;
  END IF;
END $$;

BEGIN;

-- ─── Schema changes ───
ALTER TABLE evaluation_scores
  ADD COLUMN is_not_applicable BOOLEAN NOT NULL DEFAULT FALSE;

ALTER TABLE evaluation_scores
  ALTER COLUMN score DROP NOT NULL;

ALTER TABLE evaluation_scores
  ADD CONSTRAINT evaluation_scores_score_or_na
    CHECK (
      (score IS NOT NULL AND is_not_applicable = FALSE) OR
      (score IS NULL     AND is_not_applicable = TRUE)
    );

-- ─── Audit gate ───
DO $$
DECLARE
  invalid_count INT;
  total_rows    INT;
  rated_count   INT;
  na_count      INT;
BEGIN
  SELECT COUNT(*) INTO invalid_count FROM evaluation_scores
  WHERE NOT (
    (score IS NOT NULL AND is_not_applicable = FALSE) OR
    (score IS NULL     AND is_not_applicable = TRUE)
  );
  IF invalid_count > 0 THEN
    RAISE EXCEPTION 'AUDIT FAIL — % rows violate score-or-NA invariant', invalid_count;
  END IF;

  SELECT COUNT(*) INTO total_rows FROM evaluation_scores;
  SELECT COUNT(*) INTO rated_count FROM evaluation_scores WHERE NOT is_not_applicable;
  SELECT COUNT(*) INTO na_count    FROM evaluation_scores WHERE is_not_applicable;

  IF total_rows != {expected_rows} THEN
    RAISE EXCEPTION 'AUDIT FAIL — total rows changed during migration: % (was %)',
      total_rows, {expected_rows};
  END IF;
  IF rated_count != {expected_rows} OR na_count != 0 THEN
    RAISE EXCEPTION 'AUDIT FAIL — backfill state wrong: rated=% na=% (expected rated=% na=0)',
      rated_count, na_count, {expected_rows};
  END IF;

  RAISE NOTICE 'AUDIT PASS — % rows, % rated, % N/A, all satisfy score-or-NA invariant',
    total_rows, rated_count, na_count;
END $$;

-- ─── Eyeball verification ───
SELECT 'pre-existing rows post-migration'   AS status,
       COUNT(*) FILTER (WHERE NOT is_not_applicable) AS rated,
       COUNT(*) FILTER (WHERE is_not_applicable)     AS na,
       COUNT(*)                                       AS total
FROM   evaluation_scores;

COMMIT;
"""


def main():
    sql = SQL_TEMPLATE.format(expected_rows=EXPECTED_ROWS_BEFORE)
    out = Path(__file__).parent / "phase_5c1_1_na_column.sql"
    out.write_text(sql, encoding="utf-8")
    n = sql.count("\n") + 1
    print(f"Wrote {out} ({n} lines)")
    print(f"Pre-flight: evaluation_scores has {EXPECTED_ROWS_BEFORE} rows, all score IS NOT NULL")
    print(f"Audit:      {EXPECTED_ROWS_BEFORE} rated rows after backfill, 0 N/A, 0 invalid")


if __name__ == "__main__":
    main()
