"""
Generator for migrations/phase_4_2_season_column.sql

Phase 4.2 adds a `season` column to wyscout_match_stats and backfills
historical rows. The Python helper `app.wyscout.season.derive_season`
is the source of truth; the SQL CASE expression must produce the same
strings. This script asserts that on 5 representative dates BEFORE
emitting the SQL, so a future tweak to one path without the other
won't ship.

Run from repo root:
    python migrations/_generate_phase_4_2.py

Writes:
    migrations/phase_4_2_season_column.sql

Pre-flight + audit gates inside the emitted SQL:
  - Pre-flight aborts if the column already exists (avoids accidental
    re-apply once the migration has landed).
  - Audit gate computes EXPECTED dynamically (= COUNT(*) WHERE match_date
    IS NOT NULL); rolls back if any match_date row remains NULL-season,
    or if the row count for season '2025-26' doesn't equal the expected
    pre-flight count (the spec says all current rows fall in that season
    — date range 2025-09-12 → 2026-04-16, verified before this phase
    began). The 34-row count in the original spec was stale (49 today);
    deriving the expected count dynamically keeps the migration
    correct as more rows land before commit.
"""
import sys
from datetime import date
from pathlib import Path

# Make `app` importable when running from migrations/
sys.path.insert(0, str(Path(__file__).resolve().parent.parent))
from app.wyscout.season import derive_season


# ── 5 derive_season unit tests (spec-mandated) ──────────────────────
TEST_CASES = [
    (date(2025, 9, 12),  "2025-26"),
    (date(2026, 4, 16),  "2025-26"),
    (date(2025, 7, 31),  "2024-25"),
    (date(2025, 8, 1),   "2025-26"),
    (date(2026, 8, 15),  "2026-27"),
]

print("derive_season unit tests:")
for d, expected in TEST_CASES:
    actual = derive_season(d)
    ok = actual == expected
    print(f"  derive_season({d}) = {actual!r}  (expected {expected!r})  "
          f"{'PASS' if ok else 'FAIL'}")
    assert ok, f"derive_season({d}) returned {actual!r}, expected {expected!r}"
print(f"  {len(TEST_CASES)}/{len(TEST_CASES)} PASS — SQL emission unlocked.\n")


# ── SQL artifact ────────────────────────────────────────────────────
# The SQL CASE mirrors derive_season() exactly:
#   if month >= 8:   start_year = year,        end = (year+1) % 100
#   else:            start_year = year - 1,    end = year     % 100
# LPAD to '00' handles the boundary year 2000 → '00'.
SQL = """\
-- =============================================================
-- BFA-Scout — Phase 4.2 season column + backfill
-- Generated by migrations/_generate_phase_4_2.py
-- =============================================================
-- Effects:
--   1. Pre-flight: aborts if `season` column already exists, or if any
--      existing match_date falls outside the verified 2025-26 window
--      (2025-09-12 .. 2026-04-16). The latter guards against a future
--      run after a multi-season import — at that point this migration
--      shouldn't be the one doing the backfill; rerun the generator
--      first to widen the gate.
--   2. ADD COLUMN season VARCHAR(7), nullable. Adds index.
--   3. Backfill: derive season from match_date via SQL CASE matching
--      `app.wyscout.season.derive_season()`. NULL match_date rows
--      (none today, but future-proof) keep NULL season.
--   4. Audit gate: every row with a match_date must have a season; the
--      season '2025-26' count must equal the pre-flight row count
--      (verified date range guarantees this).
--
-- Re-runnability: the pre-flight on column existence makes this a
-- one-shot; subsequent applies will RAISE before any DDL.
-- =============================================================

\\set ON_ERROR_STOP on
\\timing on

-- ─── Pre-flight (no transaction yet) ─────────────────────────────
DO $$
DECLARE
  col_exists BOOLEAN;
  oor_count  INT;
  min_d      DATE;
  max_d      DATE;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name   = 'wyscout_match_stats'
      AND column_name  = 'season'
  ) INTO col_exists;
  IF col_exists THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — wyscout_match_stats.season already exists; migration already applied';
  END IF;

  -- Date-range sanity: every match_date should fall in the verified window.
  SELECT MIN(match_date), MAX(match_date) INTO min_d, max_d
  FROM wyscout_match_stats WHERE match_date IS NOT NULL;
  IF min_d IS NULL THEN
    RAISE NOTICE 'PRE-FLIGHT NOTICE — wyscout_match_stats is empty; backfill will be a no-op';
  ELSIF min_d < DATE '2025-08-01' OR max_d >= DATE '2026-08-01' THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — match_date range % .. % extends outside the 2025-26 season; '
                    'regenerate the migration with widened audit gate first',
                    min_d, max_d;
  END IF;

  SELECT COUNT(*) INTO oor_count FROM wyscout_match_stats
   WHERE match_date IS NOT NULL
     AND (match_date < DATE '2025-08-01' OR match_date >= DATE '2026-08-01');
  IF oor_count > 0 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — % rows outside 2025-26 season window', oor_count;
  END IF;

  RAISE NOTICE 'PRE-FLIGHT PASS — date range % .. % (single season 2025-26)', min_d, max_d;
END $$;

BEGIN;

-- ─── DDL: add column + index ─────────────────────────────────────
ALTER TABLE wyscout_match_stats
  ADD COLUMN season VARCHAR(7);

CREATE INDEX IF NOT EXISTS idx_wyscout_match_stats_season
  ON wyscout_match_stats(season);

-- ─── Backfill ────────────────────────────────────────────────────
-- Mirrors app.wyscout.season.derive_season() in pure SQL:
--   if month >= 8: start = year,     end = (year + 1) % 100
--   else:          start = year - 1, end = year       % 100
-- LPAD to '00' so 2000 → '00' (no current data exercises this, but
-- the Python helper handles it the same way via %02d).
UPDATE wyscout_match_stats
SET season = CASE
    WHEN match_date IS NULL THEN NULL
    WHEN EXTRACT(MONTH FROM match_date)::INT >= 8 THEN
        EXTRACT(YEAR FROM match_date)::INT::TEXT
        || '-'
        || LPAD(((EXTRACT(YEAR FROM match_date)::INT + 1) % 100)::TEXT, 2, '0')
    ELSE
        (EXTRACT(YEAR FROM match_date)::INT - 1)::TEXT
        || '-'
        || LPAD((EXTRACT(YEAR FROM match_date)::INT % 100)::TEXT, 2, '0')
END
WHERE season IS NULL;

-- ─── Audit gate (RAISE → ROLLBACK on drift) ──────────────────────
DO $$
DECLARE
  expected     INT;
  in_2025_26   INT;
  null_with_dt INT;
BEGIN
  SELECT COUNT(*) INTO expected   FROM wyscout_match_stats WHERE match_date IS NOT NULL;
  SELECT COUNT(*) INTO in_2025_26 FROM wyscout_match_stats WHERE season = '2025-26';
  SELECT COUNT(*) INTO null_with_dt
    FROM wyscout_match_stats
    WHERE match_date IS NOT NULL AND season IS NULL;

  IF null_with_dt > 0 THEN
    RAISE EXCEPTION 'AUDIT FAIL — % rows with match_date still have NULL season', null_with_dt;
  END IF;
  IF in_2025_26 != expected THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected % rows in season 2025-26, got %',
                    expected, in_2025_26;
  END IF;

  RAISE NOTICE 'AUDIT PASS — all % rows backfilled to season 2025-26', expected;
END $$;

COMMIT;

-- ─── Eyeball table (post-commit) ─────────────────────────────────
SELECT season,
       COUNT(*)        AS rows,
       MIN(match_date) AS min_date,
       MAX(match_date) AS max_date
FROM   wyscout_match_stats
GROUP  BY season
ORDER  BY season NULLS FIRST;
"""

out = Path(__file__).parent / "phase_4_2_season_column.sql"
out.write_text(SQL, encoding="utf-8")
print(f"Wrote {out}  ({out.stat().st_size:,} bytes)")
