"""
Generator for migrations/phase_5c2_lock_and_eligibility.sql

Phase 5c-2 schema additions:
  players: 2 new admin-set residency tracking columns
  evaluations: 3 new (locked_reason, last_edited_by, last_edited_at)
               + recreate locked_by FK with ON DELETE SET NULL
               + recreate last_edited_by FK with ON DELETE SET NULL

Spec said to ADD locked_at/locked_by and to extend status CHECK to include
'locked' — but BOTH are already in place from Phase 0 (verified in
PHASE_5C2 pre-flight). This generator skips the no-ops and only does the
deltas. End state matches the spec exactly.
"""
from pathlib import Path

SQL = """\
-- =============================================================
-- BFA-Scout — Phase 5c-2 lock-workflow + residency-tracking migration
-- Generated by migrations/_generate_phase_5c2.py
-- =============================================================
-- Effects:
--   1. Pre-flight: confirms the 5 truly-new columns don't exist yet,
--      confirms locked_at/locked_by/status='locked' DO already exist
--      (so we don't accidentally re-add them).
--   2. players: ADD bahrain_residency_start_date, bahrain_residency_notes
--   3. evaluations: ADD locked_reason, last_edited_by, last_edited_at
--   4. Recreate evaluations_locked_by_fkey with ON DELETE SET NULL
--      (was default NO ACTION — would block user deletion).
--   5. Audit gate: every target column present; both FKs are SET NULL.
-- =============================================================

\\set ON_ERROR_STOP on
\\timing on

-- ─── Pre-flight ───
DO $$
DECLARE
  c TEXT;
  exists_count INT;
  status_has_locked BOOLEAN;
BEGIN
  -- 1. Truly-new columns must NOT already exist
  FOR c IN SELECT unnest(ARRAY[
      'players.bahrain_residency_start_date',
      'players.bahrain_residency_notes',
      'evaluations.locked_reason',
      'evaluations.last_edited_by',
      'evaluations.last_edited_at'
  ]) LOOP
    SELECT COUNT(*) INTO exists_count
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = split_part(c, '.', 1)
      AND column_name  = split_part(c, '.', 2);
    IF exists_count > 0 THEN
      RAISE EXCEPTION 'PRE-FLIGHT FAIL — column % already exists', c;
    END IF;
  END LOOP;

  -- 2. Pre-existing infrastructure (locked_at/locked_by/status='locked')
  --    must already be in place — otherwise the spec's environmental
  --    assumptions are wrong.
  FOR c IN SELECT unnest(ARRAY[
      'evaluations.locked_at',
      'evaluations.locked_by'
  ]) LOOP
    SELECT COUNT(*) INTO exists_count
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = split_part(c, '.', 1)
      AND column_name  = split_part(c, '.', 2);
    IF exists_count = 0 THEN
      RAISE EXCEPTION 'PRE-FLIGHT FAIL — expected pre-existing column % missing', c;
    END IF;
  END LOOP;

  SELECT EXISTS (
    SELECT 1 FROM pg_constraint
    WHERE conname = 'evaluations_status_check'
      AND pg_get_constraintdef(oid) LIKE '%locked%'
  ) INTO status_has_locked;
  IF NOT status_has_locked THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — evaluations_status_check does not include locked';
  END IF;
END $$;

BEGIN;

-- ─── players: 2 new residency-tracking cols (admin-set) ───
ALTER TABLE players
  ADD COLUMN bahrain_residency_start_date DATE,
  ADD COLUMN bahrain_residency_notes      TEXT;

-- ─── evaluations: 3 new lock+admin-edit tracking cols ───
ALTER TABLE evaluations
  ADD COLUMN locked_reason   TEXT,
  ADD COLUMN last_edited_by  INTEGER REFERENCES users(id) ON DELETE SET NULL,
  ADD COLUMN last_edited_at  TIMESTAMPTZ;

CREATE INDEX IF NOT EXISTS idx_eval_last_edited_by
  ON evaluations(last_edited_by);

-- ─── Tighten existing locked_by FK to ON DELETE SET NULL ───
ALTER TABLE evaluations
  DROP CONSTRAINT evaluations_locked_by_fkey;
ALTER TABLE evaluations
  ADD  CONSTRAINT evaluations_locked_by_fkey
       FOREIGN KEY (locked_by) REFERENCES users(id) ON DELETE SET NULL;

-- ─── Audit gate ───
DO $$
DECLARE
  cols_present INT;
  locked_by_action CHAR;
  last_edited_by_action CHAR;
BEGIN
  SELECT COUNT(*) INTO cols_present
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND ((table_name = 'players' AND column_name IN
          ('bahrain_residency_start_date','bahrain_residency_notes'))
      OR (table_name = 'evaluations' AND column_name IN
          ('locked_reason','last_edited_by','last_edited_at')));
  IF cols_present != 5 THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected 5 new columns landed, found %', cols_present;
  END IF;

  SELECT con.confdeltype INTO locked_by_action
  FROM pg_constraint con
  JOIN pg_class       rel ON rel.oid = con.conrelid
  JOIN pg_attribute   att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
  WHERE rel.relname = 'evaluations' AND att.attname = 'locked_by' AND con.contype = 'f';
  IF locked_by_action != 'n' THEN
    RAISE EXCEPTION 'AUDIT FAIL — locked_by FK confdeltype = % (expected n for SET NULL)',
      locked_by_action;
  END IF;

  SELECT con.confdeltype INTO last_edited_by_action
  FROM pg_constraint con
  JOIN pg_class       rel ON rel.oid = con.conrelid
  JOIN pg_attribute   att ON att.attrelid = rel.oid AND att.attnum = ANY(con.conkey)
  WHERE rel.relname = 'evaluations' AND att.attname = 'last_edited_by' AND con.contype = 'f';
  IF last_edited_by_action != 'n' THEN
    RAISE EXCEPTION 'AUDIT FAIL — last_edited_by FK confdeltype = % (expected n)',
      last_edited_by_action;
  END IF;

  RAISE NOTICE 'AUDIT PASS — 5 cols added, both FKs ON DELETE SET NULL';
END $$;

-- ─── Eyeball verification ───
SELECT 'players'     AS tbl, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'players'
  AND column_name IN ('bahrain_residency_start_date','bahrain_residency_notes')
UNION ALL
SELECT 'evaluations' AS tbl, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public' AND table_name = 'evaluations'
  AND column_name IN ('locked_reason','last_edited_by','last_edited_at')
ORDER BY tbl, column_name;

COMMIT;
"""


def main():
    out = Path(__file__).parent / "phase_5c2_lock_and_eligibility.sql"
    out.write_text(SQL, encoding="utf-8")
    n = SQL.count("\n") + 1
    print(f"Wrote {out} ({n} lines)")
    print("Adds 5 cols (2 on players, 3 on evaluations) + tightens 2 FKs to ON DELETE SET NULL.")


if __name__ == "__main__":
    main()
