-- =============================================================
-- BFA-Scout — Phase 5c-3: clubs table + nationality + soft-delete
-- Generated by migrations/_generate_phase_5c3.py
-- =============================================================
-- Effects:
--   1. Pre-flight: aborts if clubs table OR any target column exists.
--   2. Creates clubs table + 4 indexes; seeds 24 clubs.
--   3. Adds nationality_code + club_id to players.
--   4. Adds soft-delete trio to evaluations + CHECK consistency.
--   5. Best-effort backfill of players.club_id from current_club text
--      with FOUR patterns: exact match, ' Club' suffix, 'al-'→'al ' swap,
--      AND a fourth pattern stripping both 'Al-' from clubs.name and
--      ' Club' from current_club to handle the "Muharraq Club" /
--      "Al-Muharraq" pair the spec writer expected.
--   6. Audit gate: 24 clubs, soft-delete CHECK present.
-- =============================================================

\set ON_ERROR_STOP on
\timing on

-- ─── Pre-flight ───
DO $$
DECLARE
  c TEXT;
  exists_count INT;
  clubs_exists BOOLEAN;
BEGIN
  SELECT to_regclass('public.clubs') IS NOT NULL INTO clubs_exists;
  IF clubs_exists THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — clubs table already exists';
  END IF;
  FOR c IN SELECT unnest(ARRAY[
      'players.nationality_code',
      'players.club_id',
      'evaluations.deleted_at',
      'evaluations.deleted_by',
      'evaluations.deleted_reason'
  ]) LOOP
    SELECT COUNT(*) INTO exists_count
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = split_part(c, '.', 1)
      AND column_name  = split_part(c, '.', 2);
    IF exists_count > 0 THEN
      RAISE EXCEPTION 'PRE-FLIGHT FAIL — column % already exists', c;
    END IF;
  END LOOP;
END $$;

BEGIN;

-- ─── 1. clubs table ───
CREATE TABLE clubs (
    id          SERIAL PRIMARY KEY,
    name        VARCHAR(128) NOT NULL,
    division    VARCHAR(16)  NOT NULL
                CHECK (division IN ('premier', 'first')),
    is_active   BOOLEAN      NOT NULL DEFAULT TRUE,
    created_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    updated_at  TIMESTAMPTZ  NOT NULL DEFAULT NOW(),
    UNIQUE (name, division)
);
CREATE INDEX idx_clubs_division ON clubs(division);
CREATE INDEX idx_clubs_active   ON clubs(is_active);

-- ─── 2. players: nationality + club FK ───
ALTER TABLE players
    ADD COLUMN nationality_code CHAR(3),
    ADD COLUMN club_id          INTEGER REFERENCES clubs(id) ON DELETE SET NULL;

CREATE INDEX idx_players_nationality ON players(nationality_code);
CREATE INDEX idx_players_club_id     ON players(club_id);

-- ─── 3. evaluations: soft-delete trio + CHECK consistency ───
ALTER TABLE evaluations
    ADD COLUMN deleted_at      TIMESTAMPTZ,
    ADD COLUMN deleted_by      INTEGER REFERENCES users(id) ON DELETE SET NULL,
    ADD COLUMN deleted_reason  TEXT,
    ADD CONSTRAINT evaluations_soft_delete_consistency
        CHECK (
            (deleted_at IS NULL  AND deleted_by IS NULL  AND deleted_reason IS NULL) OR
            (deleted_at IS NOT NULL AND deleted_by IS NOT NULL
                AND deleted_reason IS NOT NULL AND char_length(deleted_reason) >= 10)
        );

CREATE INDEX idx_evaluations_deleted_at ON evaluations(deleted_at);

-- ─── 4. Seed 24 clubs ───
INSERT INTO clubs (name, division) VALUES
    ('Al-Muharraq', 'premier'),
    ('Al-Khalidiya', 'premier'),
    ('Al-Hidd', 'premier'),
    ('Malkiya Club', 'premier'),
    ('Al-Riffa', 'premier'),
    ('A''Ali FC', 'premier'),
    ('Sitra Club', 'premier'),
    ('Al-Budaiya', 'premier'),
    ('Al-Shabab Manama', 'premier'),
    ('Al-Najma', 'premier'),
    ('Al-Ahli Manama', 'premier'),
    ('Al-Bahrain SC', 'premier'),
    ('Al-Ittifaq', 'first'),
    ('East Riffa', 'first'),
    ('Manama Club', 'first'),
    ('Al-Ettihad', 'first'),
    ('Al-Hala', 'first'),
    ('Um Alhassam', 'first'),
    ('Bouri', 'first'),
    ('Busaiteen', 'first'),
    ('Isa Town', 'first'),
    ('Etehad Alreef', 'first'),
    ('Al-Tadhamun', 'first'),
    ('Galali', 'first');

-- ─── 5. Backfill players.club_id from current_club text ───
-- Four patterns; first match wins implicitly because UPDATE is idempotent.
-- The 4th pattern is the spec-extension that catches "Muharraq Club"
-- vs "Al-Muharraq", "Khalidiya" vs "Al-Khalidiya", "Riffa" vs "Al-Riffa" —
-- the cases the spec writer expected to match but the spec's 3 patterns
-- alone would have missed.
UPDATE players
SET    club_id = c.id
FROM   clubs c
WHERE  players.club_id IS NULL
  AND  players.current_club IS NOT NULL
  AND  (
        LOWER(BTRIM(players.current_club)) = LOWER(BTRIM(c.name))
     OR LOWER(BTRIM(players.current_club)) = LOWER(BTRIM(c.name)) || ' club'
     OR REPLACE(LOWER(BTRIM(players.current_club)), 'al-', 'al ') =
        REPLACE(LOWER(BTRIM(c.name)),                'al-', 'al ')
     OR LOWER(BTRIM(REGEXP_REPLACE(players.current_club, '\s*Club$', '', 'i'))) =
        LOWER(BTRIM(REGEXP_REPLACE(c.name,                '^Al-',     '', 'i')))
  );

-- ─── Audit gate ───
DO $$
DECLARE
  clubs_count INT;
  premier_count INT;
  first_count INT;
  backfilled_count INT;
  check_present BOOLEAN;
BEGIN
  SELECT COUNT(*) INTO clubs_count   FROM clubs;
  SELECT COUNT(*) INTO premier_count FROM clubs WHERE division = 'premier';
  SELECT COUNT(*) INTO first_count   FROM clubs WHERE division = 'first';
  IF clubs_count != 24 THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected 24 clubs, got %', clubs_count;
  END IF;
  IF premier_count != 12 OR first_count != 12 THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected 12+12 split, got %+%', premier_count, first_count;
  END IF;

  SELECT EXISTS(
    SELECT 1 FROM pg_constraint
    WHERE conname = 'evaluations_soft_delete_consistency'
  ) INTO check_present;
  IF NOT check_present THEN
    RAISE EXCEPTION 'AUDIT FAIL — soft-delete CHECK constraint missing';
  END IF;

  SELECT COUNT(*) INTO backfilled_count FROM players WHERE club_id IS NOT NULL;
  RAISE NOTICE 'AUDIT PASS — % clubs (% premier + % first), CHECK present, % players auto-linked',
    clubs_count, premier_count, first_count, backfilled_count;
END $$;

-- ─── Eyeball verification ───
SELECT 'clubs'                AS info, COUNT(*)::text AS n FROM clubs
UNION ALL
SELECT 'players.club_id set'  AS info, COUNT(*)::text AS n FROM players WHERE club_id IS NOT NULL
UNION ALL
SELECT 'players.club_id null' AS info, COUNT(*)::text AS n FROM players WHERE club_id IS NULL;

-- Show which players matched which club (for human review)
SELECT pl.full_name, pl.current_club AS source_text, c.name AS matched_club
FROM   players pl
LEFT JOIN clubs c ON c.id = pl.club_id
ORDER BY pl.id;

COMMIT;
