-- =============================================================
-- BFA-Scout — Phase 5c-1 schema migration
-- Generated by migrations/_generate_phase_5c1.py
-- =============================================================
-- Effects:
--   1. Pre-flight: aborts if any target column already exists or
--      existing evaluations.match_id values would violate the FK.
--   2. players: 3 new nullable columns for admin NT-eligibility.
--   3. evaluations: new match_id column + FK + index.
--   4. Audit gate: confirms the 4 columns + FK are in place.
-- =============================================================

\set ON_ERROR_STOP on
\timing on

-- ─── Pre-flight ───
DO $$
DECLARE
  c TEXT;
  exists_count INT;
BEGIN
  -- 1. None of the new columns should already exist
  FOR c IN SELECT unnest(ARRAY[
      'players.nationality_status',
      'players.eligible_from_date',
      'players.eligibility_notes_admin',
      'evaluations.match_id'
  ]) LOOP
    SELECT COUNT(*) INTO exists_count
    FROM information_schema.columns
    WHERE table_schema = 'public'
      AND table_name   = split_part(c, '.', 1)
      AND column_name  = split_part(c, '.', 2);
    IF exists_count > 0 THEN
      RAISE EXCEPTION 'PRE-FLIGHT FAIL — column % already exists', c;
    END IF;
  END LOOP;
END $$;

BEGIN;

-- ─── players: 3 new admin-NT-eligibility columns ───
ALTER TABLE players
  ADD COLUMN nationality_status     VARCHAR(32)
    CHECK (nationality_status IN
           ('bahraini','foreign_ancestry','foreign_residency','not_eligible','unknown')
           OR nationality_status IS NULL),
  ADD COLUMN eligible_from_date     DATE,
  ADD COLUMN eligibility_notes_admin TEXT;

-- ─── evaluations: new match_id column + FK to matches ───
-- (Spec said 'promote existing column' but the column didn't exist.)
ALTER TABLE evaluations
  ADD COLUMN match_id INTEGER;

ALTER TABLE evaluations
  ADD CONSTRAINT evaluations_match_id_fkey
  FOREIGN KEY (match_id) REFERENCES matches(id) ON DELETE SET NULL;

CREATE INDEX IF NOT EXISTS idx_evaluations_match_id ON evaluations (match_id);

-- ─── Audit gate ───
DO $$
DECLARE
  cols_present INT;
  fk_present   INT;
  idx_present  INT;
BEGIN
  SELECT COUNT(*) INTO cols_present
  FROM information_schema.columns
  WHERE table_schema = 'public'
    AND ((table_name = 'players' AND column_name IN
          ('nationality_status','eligible_from_date','eligibility_notes_admin'))
      OR (table_name = 'evaluations' AND column_name = 'match_id'));
  IF cols_present != 4 THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected 4 new columns, found %', cols_present;
  END IF;

  SELECT COUNT(*) INTO fk_present
  FROM pg_constraint
  WHERE conname = 'evaluations_match_id_fkey';
  IF fk_present != 1 THEN
    RAISE EXCEPTION 'AUDIT FAIL — evaluations_match_id_fkey not present';
  END IF;

  SELECT COUNT(*) INTO idx_present
  FROM pg_indexes
  WHERE schemaname = 'public' AND indexname = 'idx_evaluations_match_id';
  IF idx_present != 1 THEN
    RAISE EXCEPTION 'AUDIT FAIL — idx_evaluations_match_id not present';
  END IF;

  RAISE NOTICE 'AUDIT PASS — 3 cols on players, match_id + FK + index on evaluations';
END $$;

-- ─── Eyeball verification ───
SELECT 'players' AS tbl, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'players'
  AND column_name IN ('nationality_status','eligible_from_date','eligibility_notes_admin')
UNION ALL
SELECT 'evaluations' AS tbl, column_name, data_type
FROM information_schema.columns
WHERE table_schema = 'public'
  AND table_name = 'evaluations'
  AND column_name = 'match_id'
ORDER BY tbl, column_name;

COMMIT;
