-- =============================================================
-- BFA-Scout — Phase 5a reseed migration
-- Generated by migrations/_generate_phase_5a.py from v2-LOCKED
-- taxonomy. Do not edit by hand: re-run the generator instead.
-- =============================================================
-- Effects:
--   1. Pre-flight: aborts if evaluation_scores has rows or any
--      evaluation uses the legacy recommendation = 'not_ready'.
--   2. Reseeds criteria (55 items) and
--      position_group_criteria (303 mappings).
--   3. Adds 4 columns to evaluations (NT readiness section).
--   4. Drops + re-adds evaluations_recommendation_check with
--      the new value set (loses 'not_ready', gains 'not_at_level').
--   5. Audit assertions enforce per-position counts before COMMIT.
-- =============================================================

\set ON_ERROR_STOP on
\timing on

-- ─── Pre-flight (no transaction yet — fail fast before locking rows) ───
DO $$
DECLARE
  s_count INT;
  bad_recs INT;
BEGIN
  SELECT COUNT(*) INTO s_count FROM evaluation_scores;
  IF s_count > 0 THEN
    RAISE EXCEPTION 'ABORT: evaluation_scores has % row(s); reseed would orphan or violate FKs', s_count;
  END IF;
  SELECT COUNT(*) INTO bad_recs FROM evaluations WHERE recommendation = 'not_ready';
  IF bad_recs > 0 THEN
    RAISE EXCEPTION 'ABORT: % evaluation row(s) use legacy recommendation = not_ready; migrate them before re-running', bad_recs;
  END IF;
END $$;

BEGIN;

-- ─── Drop old criteria + their mappings ───
DELETE FROM position_group_criteria;
DELETE FROM criteria;

-- ─── Insert 55 criteria (codes use category prefix; sort_order grouped per category) ───
INSERT INTO criteria (category_id, code, name_en, name_ar, sort_order)
SELECT cc.id, v.code, v.name_en, v.name_ar, v.sort_order
FROM (VALUES
    -- TECH
    ('TECH', 'tech_first_touch'              , 'First touch quality (under pressure & in space)'                     , 'جودة استلام الكرة'                           ,  101),
    ('TECH', 'tech_passing_short'            , 'Short passing — accuracy & weight'                                   , 'التمرير القصير'                              ,  102),
    ('TECH', 'tech_passing_long'             , 'Long passing — range & accuracy'                                     , 'التمرير الطويل'                              ,  103),
    ('TECH', 'tech_passing_press'            , 'Passing under defensive pressure'                                    , 'التمرير تحت الضغط'                           ,  104),
    ('TECH', 'tech_passing_progressive'      , 'Vertical / progressive passing selection'                            , 'التمرير التقدمي'                             ,  105),
    ('TECH', 'tech_crossing'                 , 'Crossing — quality & consistency'                                    , 'جودة العرضيات'                               ,  106),
    ('TECH', 'tech_finishing'                , 'Finishing — both feet, composure in box'                             , 'التهديف'                                     ,  107),
    ('TECH', 'tech_finishing_chances'        , 'Conversion of half-chances vs. clear-cut'                            , 'استغلال الفرص'                               ,  108),
    ('TECH', 'tech_dribbling_1v1'            , '1v1 dribbling — functional (not just attempted)'                     , 'المراوغة الفعالة'                            ,  109),
    ('TECH', 'tech_dribbling_press'          , 'Carrying ball under pressure'                                        , 'التحكم تحت الضغط أثناء التقدم'               ,  110),
    ('TECH', 'tech_set_pieces_taking'        , 'Set-piece delivery quality (corners/free-kicks)'                     , 'تنفيذ الكرات الثابتة'                        ,  111),
    ('TECH', 'tech_set_pieces_attacking'     , 'Attacking set-pieces (heading/finishing in box)'                     , 'الكرات الثابتة الهجومية'                     ,  112),
    ('TECH', 'tech_heading_offensive'        , 'Aerial — offensive (attacking corners, crosses)'                     , 'الضربات الرأسية الهجومية'                    ,  113),
    ('TECH', 'tech_heading_defensive'        , 'Aerial — defensive (clearing crosses, set-piece defending)'          , 'الضربات الرأسية الدفاعية'                    ,  114),
    ('TECH', 'tech_ball_striking'            , 'Ball striking — distance shooting, free-kicks'                       , 'جودة التسديد'                                ,  115),
    ('TECH', 'tech_gk_shot_stopping'         , 'Shot stopping — reactions, positioning, handling'                    , 'التصدي'                                      ,  116),
    ('TECH', 'tech_gk_handling'              , 'Handling under pressure (catches, parries, drops)'                   , 'الإمساك بالكرة'                              ,  117),
    ('TECH', 'tech_gk_distribution'          , 'Distribution — short, long, under press'                             , 'توزيع الكرة'                                 ,  118),
    ('TECH', 'tech_gk_crosses'               , 'Cross claiming — command of area'                                    , 'التعامل مع العرضيات'                         ,  119),
    ('TECH', 'tech_gk_sweeper'               , 'Sweeping behind defensive line'                                      , 'اللعب كالليبيرو'                             ,  120),
    -- TACT
    ('TACT', 'tact_positioning_def'          , 'Defensive positioning'                                               , 'التموضع الدفاعي'                             ,  201),
    ('TACT', 'tact_positioning_att'          , 'Attacking positioning (off the ball)'                                , 'التموضع الهجومي'                             ,  202),
    ('TACT', 'tact_scanning'                 , 'Scanning frequency before receiving'                                 , 'النظر للمحيط قبل الاستلام'                   ,  203),
    ('TACT', 'tact_body_orientation'         , 'Body orientation when receiving'                                     , 'اتجاه الجسم عند الاستلام'                    ,  204),
    ('TACT', 'tact_decision_making'          , 'Decision-making speed & quality'                                     , 'اتخاذ القرار'                                ,  205),
    ('TACT', 'tact_off_ball_movement'        , 'Off-ball movement & space creation'                                  , 'الحركة بدون كرة'                             ,  206),
    ('TACT', 'tact_runs_in_behind'           , 'Runs in behind — timing & frequency'                                 , 'الجري خلف الدفاع'                            ,  207),
    ('TACT', 'tact_pressing_trigger'         , 'Pressing — recognition of triggers'                                  , 'قراءة لحظات الضغط'                           ,  208),
    ('TACT', 'tact_pressing_intensity'       , 'Pressing — intensity & sustainability'                               , 'شدة الضغط'                                   ,  209),
    ('TACT', 'tact_def_shape'                , 'Maintaining defensive shape (within unit)'                           , 'الانضباط الدفاعي'                            ,  210),
    ('TACT', 'tact_def_recovery'             , 'Recovery work after losing ball'                                     , 'العودة الدفاعية'                             ,  211),
    ('TACT', 'tact_marking'                  , 'Marking discipline (zonal & man-to-man)'                             , 'الرقابة'                                     ,  212),
    ('TACT', 'tact_back_post_cover'          , 'Back-post coverage on diagonal balls'                                , 'تغطية القائم البعيد'                         ,  213),
    ('TACT', 'tact_long_ball_cover'          , 'Covering depth on long balls / counter'                              , 'التغطية في الكرات الطويلة'                   ,  214),
    ('TACT', 'tact_one_v_one_def'            , '1v1 defending — body shape, timing'                                  , 'الدفاع الفردي'                               ,  215),
    ('TACT', 'tact_build_up'                 , 'Build-up contribution from back/middle third'                        , 'بناء الهجمة'                                 ,  216),
    ('TACT', 'tact_third_man_runs'           , 'Third-man runs / combination play'                                   , 'لعب المثلثات'                                ,  217),
    ('TACT', 'tact_communication'            , 'Tactical communication / organising teammates'                       , 'التواصل التكتيكي'                            ,  218),
    ('TACT', 'tact_transition_def_to_att'    , 'Defensive → attacking transition speed'                              , 'الانتقال من الدفاع للهجوم'                   ,  219),
    ('TACT', 'tact_transition_att_to_def'    , 'Attacking → defensive transition speed'                              , 'الانتقال من الهجوم للدفاع'                   ,  220),
    -- PHYS
    ('PHYS', 'phys_speed_acceleration'       , 'Acceleration over 5–10m'                                             , 'التسارع'                                     ,  301),
    ('PHYS', 'phys_speed_top'                , 'Top speed'                                                           , 'السرعة القصوى'                               ,  302),
    ('PHYS', 'phys_strength_duels'           , 'Strength in ground duels (50/50s, shoulder-to-shoulder)'             , 'القوة في الالتحامات'                         ,  303),
    ('PHYS', 'phys_strength_aerial'          , 'Aerial dominance (jump + power)'                                     , 'القوة في الضربات الهوائية'                   ,  304),
    ('PHYS', 'phys_agility'                  , 'Agility — change of direction'                                       , 'الرشاقة'                                     ,  305),
    ('PHYS', 'phys_stamina_90min'            , 'Stamina across 90+ minutes'                                          , 'اللياقة (90 دقيقة كاملة)'                    ,  306),
    ('PHYS', 'phys_recovery_speed'           , 'Recovery speed (chasing back)'                                       , 'سرعة العودة'                                 ,  307),
    ('PHYS', 'phys_balance'                  , 'Balance under contact'                                               , 'التوازن'                                     ,  308),
    ('PHYS', 'phys_robustness'               , 'Physical robustness (handles contact, doesn''t go down easy)'        , 'الصلابة البدنية'                             ,  309),
    -- MENT
    ('MENT', 'ment_composure'                , 'Composure under pressure'                                            , 'الهدوء تحت الضغط'                            ,  401),
    ('MENT', 'ment_leadership'               , 'Leadership — vocal & by example'                                     , 'القيادة'                                     ,  402),
    ('MENT', 'ment_concentration'            , 'Concentration over full match'                                       , 'التركيز'                                     ,  403),
    ('MENT', 'ment_resilience'               , 'Resilience after mistakes (visible in body language)'                , 'تحمل الأخطاء'                                ,  404),
    ('MENT', 'ment_work_rate'                , 'Work rate without the ball'                                          , 'الجهد بدون كرة'                              ,  405),
    ('MENT', 'ment_winning_mentality'        , 'Visible winning mentality / hunger / will to win duels'              , 'عقلية الفوز'                                 ,  406)
) AS v(cat_code, code, name_en, name_ar, sort_order)
JOIN criteria_categories cc ON cc.code = v.cat_code;

-- ─── Insert 303 position-group mappings ───
INSERT INTO position_group_criteria (position_group_id, criterion_id, sort_order)
SELECT pg.id, c.id, c.sort_order
FROM criteria c
JOIN (VALUES
    -- TECH
    ('tech_first_touch'                , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('tech_passing_short'              , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('tech_passing_long'               , ARRAY['GK','CB','FB','DM','CM','AM']),
    ('tech_passing_press'              , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('tech_passing_progressive'        , ARRAY['DM','CM','AM','FB']),
    ('tech_crossing'                   , ARRAY['FB','W','AM']),
    ('tech_finishing'                  , ARRAY['DM','CM','AM','W','ST']),
    ('tech_finishing_chances'          , ARRAY['AM','W','ST']),
    ('tech_dribbling_1v1'              , ARRAY['FB','DM','CM','AM','W','ST']),
    ('tech_dribbling_press'            , ARRAY['CM','AM','W']),
    ('tech_set_pieces_taking'          , ARRAY['CB','FB','CM','AM']),
    ('tech_set_pieces_attacking'       , ARRAY['CB','AM','ST']),
    ('tech_heading_offensive'          , ARRAY['CB','AM','ST']),
    ('tech_heading_defensive'          , ARRAY['GK','CB','FB','DM']),
    ('tech_ball_striking'              , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tech_gk_shot_stopping'           , ARRAY['GK']),
    ('tech_gk_handling'                , ARRAY['GK']),
    ('tech_gk_distribution'            , ARRAY['GK']),
    ('tech_gk_crosses'                 , ARRAY['GK']),
    ('tech_gk_sweeper'                 , ARRAY['GK']),
    -- TACT
    ('tact_positioning_def'            , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('tact_positioning_att'            , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_scanning'                   , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('tact_body_orientation'           , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_decision_making'            , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('tact_off_ball_movement'          , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_runs_in_behind'             , ARRAY['AM','W','ST']),
    ('tact_pressing_trigger'           , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_pressing_intensity'         , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_def_shape'                  , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_def_recovery'               , ARRAY['FB','CM','AM','W']),
    ('tact_marking'                    , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_back_post_cover'            , ARRAY['CB','FB','DM']),
    ('tact_long_ball_cover'            , ARRAY['CB','FB','DM']),
    ('tact_one_v_one_def'              , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_build_up'                   , ARRAY['GK','CB','FB','DM']),
    ('tact_third_man_runs'             , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_communication'              , ARRAY['GK','CB','DM','CM']),
    ('tact_transition_def_to_att'      , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('tact_transition_att_to_def'      , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    -- PHYS
    ('phys_speed_acceleration'         , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('phys_speed_top'                  , ARRAY['CB','FB','AM','W','ST']),
    ('phys_strength_duels'             , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('phys_strength_aerial'            , ARRAY['GK','CB','ST']),
    ('phys_agility'                    , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('phys_stamina_90min'              , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('phys_recovery_speed'             , ARRAY['CB','FB','DM','W']),
    ('phys_balance'                    , ARRAY['CB','FB','DM','CM','AM','W','ST']),
    ('phys_robustness'                 , ARRAY['CB','FB','DM','ST']),
    -- MENT
    ('ment_composure'                  , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('ment_leadership'                 , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('ment_concentration'              , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('ment_resilience'                 , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('ment_work_rate'                  , ARRAY['GK','CB','FB','DM','CM','AM','W','ST']),
    ('ment_winning_mentality'          , ARRAY['GK','CB','FB','DM','CM','AM','W','ST'])
) AS m(criterion_code, group_codes) ON c.code = m.criterion_code
JOIN position_groups pg ON pg.code = ANY(m.group_codes);

-- ─── NT-readiness columns + recommendation CHECK swap ───
ALTER TABLE evaluations
  ADD COLUMN nt_readiness_level VARCHAR(16)
    CHECK (nt_readiness_level IN ('senior','u23','u20','u17','not_ready') OR nt_readiness_level IS NULL),
  ADD COLUMN eligibility_status VARCHAR(32)
    CHECK (eligibility_status IN ('bahraini','foreign_residency','foreign_ancestry','foreign_other','not_eligible','unknown') OR eligibility_status IS NULL),
  ADD COLUMN eligibility_notes  TEXT,
  ADD COLUMN comparable_player  VARCHAR(255);

ALTER TABLE evaluations DROP CONSTRAINT evaluations_recommendation_check;
ALTER TABLE evaluations ADD CONSTRAINT evaluations_recommendation_check
  CHECK (recommendation IN ('call_up','shortlist','monitor','not_at_level','release') OR recommendation IS NULL);

-- ─── Audit: assert each position-group's per-category counts match the v2 spec ───
DO $$
DECLARE
  r RECORD;
  expected JSONB := jsonb_build_object(
    'GK', jsonb_build_object('tech',10,'tact',5,'phys',3,'ment',6,'total',24),
    'CB', jsonb_build_object('tech',9,'tact',18,'phys',9,'ment',6,'total',42),
    'FB', jsonb_build_object('tech',10,'tact',18,'phys',8,'ment',6,'total',42),
    'DM', jsonb_build_object('tech',9,'tact',18,'phys',7,'ment',6,'total',40),
    'CM', jsonb_build_object('tech',10,'tact',16,'phys',5,'ment',6,'total',37),
    'AM', jsonb_build_object('tech',14,'tact',16,'phys',6,'ment',6,'total',42),
    'W', jsonb_build_object('tech',9,'tact',16,'phys',7,'ment',6,'total',38),
    'ST', jsonb_build_object('tech',9,'tact',15,'phys',8,'ment',6,'total',38)
  );
BEGIN
  FOR r IN
    SELECT pg.code AS grp,
           COUNT(*) FILTER (WHERE c.code LIKE 'tech_%') AS tech,
           COUNT(*) FILTER (WHERE c.code LIKE 'tact_%') AS tact,
           COUNT(*) FILTER (WHERE c.code LIKE 'phys_%') AS phys,
           COUNT(*) FILTER (WHERE c.code LIKE 'ment_%') AS ment,
           COUNT(*)                                     AS total
    FROM position_groups pg
    LEFT JOIN position_group_criteria pgc ON pgc.position_group_id = pg.id
    LEFT JOIN criteria c                  ON c.id = pgc.criterion_id
    GROUP BY pg.code, pg.sort_order
    ORDER BY pg.sort_order
  LOOP
    IF (expected->r.grp->>'tech')::int  != r.tech
    OR (expected->r.grp->>'tact')::int  != r.tact
    OR (expected->r.grp->>'phys')::int  != r.phys
    OR (expected->r.grp->>'ment')::int  != r.ment
    OR (expected->r.grp->>'total')::int != r.total THEN
      RAISE EXCEPTION 'AUDIT FAIL %: got tech=% tact=% phys=% ment=% total=% (expected %)',
        r.grp, r.tech, r.tact, r.phys, r.ment, r.total, expected->r.grp;
    END IF;
  END LOOP;
  RAISE NOTICE 'AUDIT PASS — all 8 position groups match v2-LOCKED counts';
END $$;

-- ─── Human-eyeball audit table (printed before COMMIT) ───
SELECT pg.code AS grp,
       COUNT(*) FILTER (WHERE c.code LIKE 'tech_%') AS tech,
       COUNT(*) FILTER (WHERE c.code LIKE 'tact_%') AS tact,
       COUNT(*) FILTER (WHERE c.code LIKE 'phys_%') AS phys,
       COUNT(*) FILTER (WHERE c.code LIKE 'ment_%') AS ment,
       COUNT(*)                                     AS total
FROM position_groups pg
LEFT JOIN position_group_criteria pgc ON pgc.position_group_id = pg.id
LEFT JOIN criteria c                  ON c.id = pgc.criterion_id
GROUP BY pg.code, pg.sort_order
ORDER BY pg.sort_order;

COMMIT;
