-- =============================================================
-- BFA-Scout — Phase 4.2 season column + backfill
-- Generated by migrations/_generate_phase_4_2.py
-- =============================================================
-- Effects:
--   1. Pre-flight: aborts if `season` column already exists, or if any
--      existing match_date falls outside the verified 2025-26 window
--      (2025-09-12 .. 2026-04-16). The latter guards against a future
--      run after a multi-season import — at that point this migration
--      shouldn't be the one doing the backfill; rerun the generator
--      first to widen the gate.
--   2. ADD COLUMN season VARCHAR(7), nullable. Adds index.
--   3. Backfill: derive season from match_date via SQL CASE matching
--      `app.wyscout.season.derive_season()`. NULL match_date rows
--      (none today, but future-proof) keep NULL season.
--   4. Audit gate: every row with a match_date must have a season; the
--      season '2025-26' count must equal the pre-flight row count
--      (verified date range guarantees this).
--
-- Re-runnability: the pre-flight on column existence makes this a
-- one-shot; subsequent applies will RAISE before any DDL.
-- =============================================================

\set ON_ERROR_STOP on
\timing on

-- ─── Pre-flight (no transaction yet) ─────────────────────────────
DO $$
DECLARE
  col_exists BOOLEAN;
  oor_count  INT;
  min_d      DATE;
  max_d      DATE;
BEGIN
  SELECT EXISTS (
    SELECT 1 FROM information_schema.columns
    WHERE table_schema = current_schema()
      AND table_name   = 'wyscout_match_stats'
      AND column_name  = 'season'
  ) INTO col_exists;
  IF col_exists THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — wyscout_match_stats.season already exists; migration already applied';
  END IF;

  -- Date-range sanity: every match_date should fall in the verified window.
  SELECT MIN(match_date), MAX(match_date) INTO min_d, max_d
  FROM wyscout_match_stats WHERE match_date IS NOT NULL;
  IF min_d IS NULL THEN
    RAISE NOTICE 'PRE-FLIGHT NOTICE — wyscout_match_stats is empty; backfill will be a no-op';
  ELSIF min_d < DATE '2025-08-01' OR max_d >= DATE '2026-08-01' THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — match_date range % .. % extends outside the 2025-26 season; '
                    'regenerate the migration with widened audit gate first',
                    min_d, max_d;
  END IF;

  SELECT COUNT(*) INTO oor_count FROM wyscout_match_stats
   WHERE match_date IS NOT NULL
     AND (match_date < DATE '2025-08-01' OR match_date >= DATE '2026-08-01');
  IF oor_count > 0 THEN
    RAISE EXCEPTION 'PRE-FLIGHT FAIL — % rows outside 2025-26 season window', oor_count;
  END IF;

  RAISE NOTICE 'PRE-FLIGHT PASS — date range % .. % (single season 2025-26)', min_d, max_d;
END $$;

BEGIN;

-- ─── DDL: add column + index ─────────────────────────────────────
ALTER TABLE wyscout_match_stats
  ADD COLUMN season VARCHAR(7);

CREATE INDEX IF NOT EXISTS idx_wyscout_match_stats_season
  ON wyscout_match_stats(season);

-- ─── Backfill ────────────────────────────────────────────────────
-- Mirrors app.wyscout.season.derive_season() in pure SQL:
--   if month >= 8: start = year,     end = (year + 1) % 100
--   else:          start = year - 1, end = year       % 100
-- LPAD to '00' so 2000 → '00' (no current data exercises this, but
-- the Python helper handles it the same way via %02d).
UPDATE wyscout_match_stats
SET season = CASE
    WHEN match_date IS NULL THEN NULL
    WHEN EXTRACT(MONTH FROM match_date)::INT >= 8 THEN
        EXTRACT(YEAR FROM match_date)::INT::TEXT
        || '-'
        || LPAD(((EXTRACT(YEAR FROM match_date)::INT + 1) % 100)::TEXT, 2, '0')
    ELSE
        (EXTRACT(YEAR FROM match_date)::INT - 1)::TEXT
        || '-'
        || LPAD((EXTRACT(YEAR FROM match_date)::INT % 100)::TEXT, 2, '0')
END
WHERE season IS NULL;

-- ─── Audit gate (RAISE → ROLLBACK on drift) ──────────────────────
DO $$
DECLARE
  expected     INT;
  in_2025_26   INT;
  null_with_dt INT;
BEGIN
  SELECT COUNT(*) INTO expected   FROM wyscout_match_stats WHERE match_date IS NOT NULL;
  SELECT COUNT(*) INTO in_2025_26 FROM wyscout_match_stats WHERE season = '2025-26';
  SELECT COUNT(*) INTO null_with_dt
    FROM wyscout_match_stats
    WHERE match_date IS NOT NULL AND season IS NULL;

  IF null_with_dt > 0 THEN
    RAISE EXCEPTION 'AUDIT FAIL — % rows with match_date still have NULL season', null_with_dt;
  END IF;
  IF in_2025_26 != expected THEN
    RAISE EXCEPTION 'AUDIT FAIL — expected % rows in season 2025-26, got %',
                    expected, in_2025_26;
  END IF;

  RAISE NOTICE 'AUDIT PASS — all % rows backfilled to season 2025-26', expected;
END $$;

COMMIT;

-- ─── Eyeball table (post-commit) ─────────────────────────────────
SELECT season,
       COUNT(*)        AS rows,
       MIN(match_date) AS min_date,
       MAX(match_date) AS max_date
FROM   wyscout_match_stats
GROUP  BY season
ORDER  BY season NULLS FIRST;
