"""
FIFA / ISO 3166-1 nationality dictionary (Phase 5c-3).

Generated once via migrations/_generate_nationalities.py from `pycountry`.
No runtime dependency on pycountry — this file is the source of truth.

Bahrain (BHR) is pinned first since this is a Bahrain-focused platform;
the rest is alphabetical by EN name.
Total: 249 entries.
"""

NATIONALITY_CHOICES = [
    (  'BHR', 'Bahrain'),
    (  'AFG', 'Afghanistan'),
    (  'ALB', 'Albania'),
    (  'DZA', 'Algeria'),
    (  'ASM', 'American Samoa'),
    (  'AND', 'Andorra'),
    (  'AGO', 'Angola'),
    (  'AIA', 'Anguilla'),
    (  'ATA', 'Antarctica'),
    (  'ATG', 'Antigua and Barbuda'),
    (  'ARG', 'Argentina'),
    (  'ARM', 'Armenia'),
    (  'ABW', 'Aruba'),
    (  'AUS', 'Australia'),
    (  'AUT', 'Austria'),
    (  'AZE', 'Azerbaijan'),
    (  'BHS', 'Bahamas'),
    (  'BGD', 'Bangladesh'),
    (  'BRB', 'Barbados'),
    (  'BLR', 'Belarus'),
    (  'BEL', 'Belgium'),
    (  'BLZ', 'Belize'),
    (  'BEN', 'Benin'),
    (  'BMU', 'Bermuda'),
    (  'BTN', 'Bhutan'),
    (  'BOL', 'Bolivia, Plurinational State of'),
    (  'BES', 'Bonaire, Sint Eustatius and Saba'),
    (  'BIH', 'Bosnia and Herzegovina'),
    (  'BWA', 'Botswana'),
    (  'BVT', 'Bouvet Island'),
    (  'BRA', 'Brazil'),
    (  'IOT', 'British Indian Ocean Territory'),
    (  'BRN', 'Brunei Darussalam'),
    (  'BGR', 'Bulgaria'),
    (  'BFA', 'Burkina Faso'),
    (  'BDI', 'Burundi'),
    (  'CPV', 'Cabo Verde'),
    (  'KHM', 'Cambodia'),
    (  'CMR', 'Cameroon'),
    (  'CAN', 'Canada'),
    (  'CYM', 'Cayman Islands'),
    (  'CAF', 'Central African Republic'),
    (  'TCD', 'Chad'),
    (  'CHL', 'Chile'),
    (  'CHN', 'China'),
    (  'CXR', 'Christmas Island'),
    (  'CCK', 'Cocos (Keeling) Islands'),
    (  'COL', 'Colombia'),
    (  'COM', 'Comoros'),
    (  'COG', 'Congo'),
    (  'COD', 'Congo, The Democratic Republic of the'),
    (  'COK', 'Cook Islands'),
    (  'CRI', 'Costa Rica'),
    (  'HRV', 'Croatia'),
    (  'CUB', 'Cuba'),
    (  'CUW', 'Curaçao'),
    (  'CYP', 'Cyprus'),
    (  'CZE', 'Czechia'),
    (  'CIV', 'Côte d\'Ivoire'),
    (  'DNK', 'Denmark'),
    (  'DJI', 'Djibouti'),
    (  'DMA', 'Dominica'),
    (  'DOM', 'Dominican Republic'),
    (  'ECU', 'Ecuador'),
    (  'EGY', 'Egypt'),
    (  'SLV', 'El Salvador'),
    (  'GNQ', 'Equatorial Guinea'),
    (  'ERI', 'Eritrea'),
    (  'EST', 'Estonia'),
    (  'SWZ', 'Eswatini'),
    (  'ETH', 'Ethiopia'),
    (  'FLK', 'Falkland Islands (Malvinas)'),
    (  'FRO', 'Faroe Islands'),
    (  'FJI', 'Fiji'),
    (  'FIN', 'Finland'),
    (  'FRA', 'France'),
    (  'GUF', 'French Guiana'),
    (  'PYF', 'French Polynesia'),
    (  'ATF', 'French Southern Territories'),
    (  'GAB', 'Gabon'),
    (  'GMB', 'Gambia'),
    (  'GEO', 'Georgia'),
    (  'DEU', 'Germany'),
    (  'GHA', 'Ghana'),
    (  'GIB', 'Gibraltar'),
    (  'GRC', 'Greece'),
    (  'GRL', 'Greenland'),
    (  'GRD', 'Grenada'),
    (  'GLP', 'Guadeloupe'),
    (  'GUM', 'Guam'),
    (  'GTM', 'Guatemala'),
    (  'GGY', 'Guernsey'),
    (  'GIN', 'Guinea'),
    (  'GNB', 'Guinea-Bissau'),
    (  'GUY', 'Guyana'),
    (  'HTI', 'Haiti'),
    (  'HMD', 'Heard Island and McDonald Islands'),
    (  'VAT', 'Holy See (Vatican City State)'),
    (  'HND', 'Honduras'),
    (  'HKG', 'Hong Kong'),
    (  'HUN', 'Hungary'),
    (  'ISL', 'Iceland'),
    (  'IND', 'India'),
    (  'IDN', 'Indonesia'),
    (  'IRN', 'Iran, Islamic Republic of'),
    (  'IRQ', 'Iraq'),
    (  'IRL', 'Ireland'),
    (  'IMN', 'Isle of Man'),
    (  'ISR', 'Israel'),
    (  'ITA', 'Italy'),
    (  'JAM', 'Jamaica'),
    (  'JPN', 'Japan'),
    (  'JEY', 'Jersey'),
    (  'JOR', 'Jordan'),
    (  'KAZ', 'Kazakhstan'),
    (  'KEN', 'Kenya'),
    (  'KIR', 'Kiribati'),
    (  'PRK', 'Korea, Democratic People\'s Republic of'),
    (  'KOR', 'Korea, Republic of'),
    (  'KWT', 'Kuwait'),
    (  'KGZ', 'Kyrgyzstan'),
    (  'LAO', 'Lao People\'s Democratic Republic'),
    (  'LVA', 'Latvia'),
    (  'LBN', 'Lebanon'),
    (  'LSO', 'Lesotho'),
    (  'LBR', 'Liberia'),
    (  'LBY', 'Libya'),
    (  'LIE', 'Liechtenstein'),
    (  'LTU', 'Lithuania'),
    (  'LUX', 'Luxembourg'),
    (  'MAC', 'Macao'),
    (  'MDG', 'Madagascar'),
    (  'MWI', 'Malawi'),
    (  'MYS', 'Malaysia'),
    (  'MDV', 'Maldives'),
    (  'MLI', 'Mali'),
    (  'MLT', 'Malta'),
    (  'MHL', 'Marshall Islands'),
    (  'MTQ', 'Martinique'),
    (  'MRT', 'Mauritania'),
    (  'MUS', 'Mauritius'),
    (  'MYT', 'Mayotte'),
    (  'MEX', 'Mexico'),
    (  'FSM', 'Micronesia, Federated States of'),
    (  'MDA', 'Moldova, Republic of'),
    (  'MCO', 'Monaco'),
    (  'MNG', 'Mongolia'),
    (  'MNE', 'Montenegro'),
    (  'MSR', 'Montserrat'),
    (  'MAR', 'Morocco'),
    (  'MOZ', 'Mozambique'),
    (  'MMR', 'Myanmar'),
    (  'NAM', 'Namibia'),
    (  'NRU', 'Nauru'),
    (  'NPL', 'Nepal'),
    (  'NLD', 'Netherlands'),
    (  'NCL', 'New Caledonia'),
    (  'NZL', 'New Zealand'),
    (  'NIC', 'Nicaragua'),
    (  'NER', 'Niger'),
    (  'NGA', 'Nigeria'),
    (  'NIU', 'Niue'),
    (  'NFK', 'Norfolk Island'),
    (  'MKD', 'North Macedonia'),
    (  'MNP', 'Northern Mariana Islands'),
    (  'NOR', 'Norway'),
    (  'OMN', 'Oman'),
    (  'PAK', 'Pakistan'),
    (  'PLW', 'Palau'),
    (  'PSE', 'Palestine, State of'),
    (  'PAN', 'Panama'),
    (  'PNG', 'Papua New Guinea'),
    (  'PRY', 'Paraguay'),
    (  'PER', 'Peru'),
    (  'PHL', 'Philippines'),
    (  'PCN', 'Pitcairn'),
    (  'POL', 'Poland'),
    (  'PRT', 'Portugal'),
    (  'PRI', 'Puerto Rico'),
    (  'QAT', 'Qatar'),
    (  'ROU', 'Romania'),
    (  'RUS', 'Russian Federation'),
    (  'RWA', 'Rwanda'),
    (  'REU', 'Réunion'),
    (  'BLM', 'Saint Barthélemy'),
    (  'SHN', 'Saint Helena, Ascension and Tristan da Cunha'),
    (  'KNA', 'Saint Kitts and Nevis'),
    (  'LCA', 'Saint Lucia'),
    (  'MAF', 'Saint Martin (French part)'),
    (  'SPM', 'Saint Pierre and Miquelon'),
    (  'VCT', 'Saint Vincent and the Grenadines'),
    (  'WSM', 'Samoa'),
    (  'SMR', 'San Marino'),
    (  'STP', 'Sao Tome and Principe'),
    (  'SAU', 'Saudi Arabia'),
    (  'SEN', 'Senegal'),
    (  'SRB', 'Serbia'),
    (  'SYC', 'Seychelles'),
    (  'SLE', 'Sierra Leone'),
    (  'SGP', 'Singapore'),
    (  'SXM', 'Sint Maarten (Dutch part)'),
    (  'SVK', 'Slovakia'),
    (  'SVN', 'Slovenia'),
    (  'SLB', 'Solomon Islands'),
    (  'SOM', 'Somalia'),
    (  'ZAF', 'South Africa'),
    (  'SGS', 'South Georgia and the South Sandwich Islands'),
    (  'SSD', 'South Sudan'),
    (  'ESP', 'Spain'),
    (  'LKA', 'Sri Lanka'),
    (  'SDN', 'Sudan'),
    (  'SUR', 'Suriname'),
    (  'SJM', 'Svalbard and Jan Mayen'),
    (  'SWE', 'Sweden'),
    (  'CHE', 'Switzerland'),
    (  'SYR', 'Syrian Arab Republic'),
    (  'TWN', 'Taiwan, Province of China'),
    (  'TJK', 'Tajikistan'),
    (  'TZA', 'Tanzania, United Republic of'),
    (  'THA', 'Thailand'),
    (  'TLS', 'Timor-Leste'),
    (  'TGO', 'Togo'),
    (  'TKL', 'Tokelau'),
    (  'TON', 'Tonga'),
    (  'TTO', 'Trinidad and Tobago'),
    (  'TUN', 'Tunisia'),
    (  'TKM', 'Turkmenistan'),
    (  'TCA', 'Turks and Caicos Islands'),
    (  'TUV', 'Tuvalu'),
    (  'TUR', 'Türkiye'),
    (  'UGA', 'Uganda'),
    (  'UKR', 'Ukraine'),
    (  'ARE', 'United Arab Emirates'),
    (  'GBR', 'United Kingdom'),
    (  'USA', 'United States'),
    (  'UMI', 'United States Minor Outlying Islands'),
    (  'URY', 'Uruguay'),
    (  'UZB', 'Uzbekistan'),
    (  'VUT', 'Vanuatu'),
    (  'VEN', 'Venezuela, Bolivarian Republic of'),
    (  'VNM', 'Viet Nam'),
    (  'VGB', 'Virgin Islands, British'),
    (  'VIR', 'Virgin Islands, U.S.'),
    (  'WLF', 'Wallis and Futuna'),
    (  'ESH', 'Western Sahara'),
    (  'YEM', 'Yemen'),
    (  'ZMB', 'Zambia'),
    (  'ZWE', 'Zimbabwe'),
    (  'ALA', 'Åland Islands'),
]

NATIONALITY_LABEL = dict(NATIONALITY_CHOICES)


# alpha-3 → alpha-2 lookup for flag-emoji conversion
# 249 entries
ALPHA3_TO_ALPHA2 = {
    'ABW': 'AW',
    'AFG': 'AF',
    'AGO': 'AO',
    'AIA': 'AI',
    'ALA': 'AX',
    'ALB': 'AL',
    'AND': 'AD',
    'ARE': 'AE',
    'ARG': 'AR',
    'ARM': 'AM',
    'ASM': 'AS',
    'ATA': 'AQ',
    'ATF': 'TF',
    'ATG': 'AG',
    'AUS': 'AU',
    'AUT': 'AT',
    'AZE': 'AZ',
    'BDI': 'BI',
    'BEL': 'BE',
    'BEN': 'BJ',
    'BES': 'BQ',
    'BFA': 'BF',
    'BGD': 'BD',
    'BGR': 'BG',
    'BHR': 'BH',
    'BHS': 'BS',
    'BIH': 'BA',
    'BLM': 'BL',
    'BLR': 'BY',
    'BLZ': 'BZ',
    'BMU': 'BM',
    'BOL': 'BO',
    'BRA': 'BR',
    'BRB': 'BB',
    'BRN': 'BN',
    'BTN': 'BT',
    'BVT': 'BV',
    'BWA': 'BW',
    'CAF': 'CF',
    'CAN': 'CA',
    'CCK': 'CC',
    'CHE': 'CH',
    'CHL': 'CL',
    'CHN': 'CN',
    'CIV': 'CI',
    'CMR': 'CM',
    'COD': 'CD',
    'COG': 'CG',
    'COK': 'CK',
    'COL': 'CO',
    'COM': 'KM',
    'CPV': 'CV',
    'CRI': 'CR',
    'CUB': 'CU',
    'CUW': 'CW',
    'CXR': 'CX',
    'CYM': 'KY',
    'CYP': 'CY',
    'CZE': 'CZ',
    'DEU': 'DE',
    'DJI': 'DJ',
    'DMA': 'DM',
    'DNK': 'DK',
    'DOM': 'DO',
    'DZA': 'DZ',
    'ECU': 'EC',
    'EGY': 'EG',
    'ERI': 'ER',
    'ESH': 'EH',
    'ESP': 'ES',
    'EST': 'EE',
    'ETH': 'ET',
    'FIN': 'FI',
    'FJI': 'FJ',
    'FLK': 'FK',
    'FRA': 'FR',
    'FRO': 'FO',
    'FSM': 'FM',
    'GAB': 'GA',
    'GBR': 'GB',
    'GEO': 'GE',
    'GGY': 'GG',
    'GHA': 'GH',
    'GIB': 'GI',
    'GIN': 'GN',
    'GLP': 'GP',
    'GMB': 'GM',
    'GNB': 'GW',
    'GNQ': 'GQ',
    'GRC': 'GR',
    'GRD': 'GD',
    'GRL': 'GL',
    'GTM': 'GT',
    'GUF': 'GF',
    'GUM': 'GU',
    'GUY': 'GY',
    'HKG': 'HK',
    'HMD': 'HM',
    'HND': 'HN',
    'HRV': 'HR',
    'HTI': 'HT',
    'HUN': 'HU',
    'IDN': 'ID',
    'IMN': 'IM',
    'IND': 'IN',
    'IOT': 'IO',
    'IRL': 'IE',
    'IRN': 'IR',
    'IRQ': 'IQ',
    'ISL': 'IS',
    'ISR': 'IL',
    'ITA': 'IT',
    'JAM': 'JM',
    'JEY': 'JE',
    'JOR': 'JO',
    'JPN': 'JP',
    'KAZ': 'KZ',
    'KEN': 'KE',
    'KGZ': 'KG',
    'KHM': 'KH',
    'KIR': 'KI',
    'KNA': 'KN',
    'KOR': 'KR',
    'KWT': 'KW',
    'LAO': 'LA',
    'LBN': 'LB',
    'LBR': 'LR',
    'LBY': 'LY',
    'LCA': 'LC',
    'LIE': 'LI',
    'LKA': 'LK',
    'LSO': 'LS',
    'LTU': 'LT',
    'LUX': 'LU',
    'LVA': 'LV',
    'MAC': 'MO',
    'MAF': 'MF',
    'MAR': 'MA',
    'MCO': 'MC',
    'MDA': 'MD',
    'MDG': 'MG',
    'MDV': 'MV',
    'MEX': 'MX',
    'MHL': 'MH',
    'MKD': 'MK',
    'MLI': 'ML',
    'MLT': 'MT',
    'MMR': 'MM',
    'MNE': 'ME',
    'MNG': 'MN',
    'MNP': 'MP',
    'MOZ': 'MZ',
    'MRT': 'MR',
    'MSR': 'MS',
    'MTQ': 'MQ',
    'MUS': 'MU',
    'MWI': 'MW',
    'MYS': 'MY',
    'MYT': 'YT',
    'NAM': 'NA',
    'NCL': 'NC',
    'NER': 'NE',
    'NFK': 'NF',
    'NGA': 'NG',
    'NIC': 'NI',
    'NIU': 'NU',
    'NLD': 'NL',
    'NOR': 'NO',
    'NPL': 'NP',
    'NRU': 'NR',
    'NZL': 'NZ',
    'OMN': 'OM',
    'PAK': 'PK',
    'PAN': 'PA',
    'PCN': 'PN',
    'PER': 'PE',
    'PHL': 'PH',
    'PLW': 'PW',
    'PNG': 'PG',
    'POL': 'PL',
    'PRI': 'PR',
    'PRK': 'KP',
    'PRT': 'PT',
    'PRY': 'PY',
    'PSE': 'PS',
    'PYF': 'PF',
    'QAT': 'QA',
    'REU': 'RE',
    'ROU': 'RO',
    'RUS': 'RU',
    'RWA': 'RW',
    'SAU': 'SA',
    'SDN': 'SD',
    'SEN': 'SN',
    'SGP': 'SG',
    'SGS': 'GS',
    'SHN': 'SH',
    'SJM': 'SJ',
    'SLB': 'SB',
    'SLE': 'SL',
    'SLV': 'SV',
    'SMR': 'SM',
    'SOM': 'SO',
    'SPM': 'PM',
    'SRB': 'RS',
    'SSD': 'SS',
    'STP': 'ST',
    'SUR': 'SR',
    'SVK': 'SK',
    'SVN': 'SI',
    'SWE': 'SE',
    'SWZ': 'SZ',
    'SXM': 'SX',
    'SYC': 'SC',
    'SYR': 'SY',
    'TCA': 'TC',
    'TCD': 'TD',
    'TGO': 'TG',
    'THA': 'TH',
    'TJK': 'TJ',
    'TKL': 'TK',
    'TKM': 'TM',
    'TLS': 'TL',
    'TON': 'TO',
    'TTO': 'TT',
    'TUN': 'TN',
    'TUR': 'TR',
    'TUV': 'TV',
    'TWN': 'TW',
    'TZA': 'TZ',
    'UGA': 'UG',
    'UKR': 'UA',
    'UMI': 'UM',
    'URY': 'UY',
    'USA': 'US',
    'UZB': 'UZ',
    'VAT': 'VA',
    'VCT': 'VC',
    'VEN': 'VE',
    'VGB': 'VG',
    'VIR': 'VI',
    'VNM': 'VN',
    'VUT': 'VU',
    'WLF': 'WF',
    'WSM': 'WS',
    'YEM': 'YE',
    'ZAF': 'ZA',
    'ZMB': 'ZM',
    'ZWE': 'ZW',
}


def flag_emoji(alpha3_code: str) -> str:
    """ISO 3166-1 alpha-3 → flag emoji via Unicode regional indicators."""
    if not alpha3_code or len(alpha3_code) != 3:
        return ''
    alpha2 = ALPHA3_TO_ALPHA2.get(alpha3_code.upper())
    if not alpha2 or len(alpha2) != 2:
        return ''
    base = 0x1F1E6
    return chr(base + ord(alpha2[0]) - ord('A')) + chr(base + ord(alpha2[1]) - ord('A'))
